---
title: Dental Solutions
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  referrals:
    title: Referrals
    output: false
  team:
    title: Team
    output: false
  testimonials:
    title: Testimonials
    output: false
  treatments:
    title: Treatments
    output: false
  uploads:
    title: Uploads
    output: true
description: Treatments include Veneers, Whitening, Implants, Cosmetic crowns, Straightening
  teeth, Denture stabilisation, Smile makeovers
tagline: Treatments include Veneers, Whitening, Implants, Cosmetic crowns, Straightening
  teeth, Denture stabilisation, Smile makeovers
url: http://dentalsolutionsni.com
contact:
  facebook: https://www.facebook.com/cosmeticdentist1/info/?section=hours&tab=page_info
  address: 23 Cherry Drive, Eglinton, BT47 3US
  tel: 02871811447
  tel_spaced: 028 7181 1447
  email: info@dentalsolutionsni.com
  directions: https://www.google.co.uk/maps/dir/''/23+Cherry+Dr,+Eglinton,+Londonderry,+Derry+BT47+3US/data=!4m5!4m4!1m0!1m2!1m1!1s0x48600942ce9610bd:0xa068bc53e821ec12?sa=X&ved=0ahUKEwjvjI-p0PfLAhXDQJoKHabwCPwQwwUIHjAA
  google: https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=dental+solutions+ni&lrd=0x48600942cbe9c45d:0xef4243af857d5cf1,3,,
  form: http://mailthis.to/dentalsolutions
  feedback: http://dentalsolutionsni.com/thank-you/
  appointment: https://soe2olb.3pointdata.com/soe/new/Dental%20Solutions?pid=UKEGU01
author:
  name: Dental Solutions
  email: info@dentalsolutionsni.com
  uri: http://dentalsolutionsni.com
  bio: Treatments include Veneers, Whitening, Implants, Cosmetic crowns, Straightening
    teeth, Denture stabilisation, Smile makeovers
source: src
destination: serve
googleAnalytics: UA-XXXXX-X
future: true
show_drafts: true
lsi: false
limit_posts: 30
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - tables
  - fenced_code_blocks
  - autolink
  - smart
  - strikethrough
  - superscript
  - underline
  - highlight
  - footnotes
highlighter: true
gems:
- jekyll-redirect-from
- jekyll-paginate
